#!/bin/bash

if [ ! -e ".bigcloneeval" ]
then
	echo "listTools must be executed from within the commands directory."
	exit -1
fi
cd ..
java -cp "C:/Users/leopa/BigCloneEval/bin;C:/Users/leopa/BigCloneEval/libs/*" tasks.ListTools "$@"
